# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.protos_generated import room_pb2 as room__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in room_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RoomServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRoom = channel.unary_unary(
                '/room.RoomService/AddRoom',
                request_serializer=room__pb2.AddRoomRequest.SerializeToString,
                response_deserializer=room__pb2.AddRoomResponse.FromString,
                _registered_method=True)
        self.RemoveRoom = channel.unary_unary(
                '/room.RoomService/RemoveRoom',
                request_serializer=room__pb2.RemoveRoomRequest.SerializeToString,
                response_deserializer=room__pb2.RemoveRoomResponse.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_unary(
                '/room.RoomService/ListRooms',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=room__pb2.ListRoomsResponse.FromString,
                _registered_method=True)
        self.GetRoom = channel.unary_unary(
                '/room.RoomService/GetRoom',
                request_serializer=room__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=room__pb2.GetRoomResponse.FromString,
                _registered_method=True)


class RoomServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoom,
                    request_deserializer=room__pb2.AddRoomRequest.FromString,
                    response_serializer=room__pb2.AddRoomResponse.SerializeToString,
            ),
            'RemoveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRoom,
                    request_deserializer=room__pb2.RemoveRoomRequest.FromString,
                    response_serializer=room__pb2.RemoveRoomResponse.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=room__pb2.ListRoomsResponse.SerializeToString,
            ),
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=room__pb2.GetRoomRequest.FromString,
                    response_serializer=room__pb2.GetRoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'room.RoomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('room.RoomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.RoomService/AddRoom',
            room__pb2.AddRoomRequest.SerializeToString,
            room__pb2.AddRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.RoomService/RemoveRoom',
            room__pb2.RemoveRoomRequest.SerializeToString,
            room__pb2.RemoveRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.RoomService/ListRooms',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            room__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/room.RoomService/GetRoom',
            room__pb2.GetRoomRequest.SerializeToString,
            room__pb2.GetRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
